# Generated by Django 2.0.7 on 2018-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='remmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('WU', 'Western Union'), ('MG', 'MoneyGram'), ('EM', 'Express Money'), ('RI', 'Ria'), ('EM', 'Placid')], default='WU', max_length=2)),
            ],
        ),
    ]
