# Generated by Django 2.0.7 on 2018-07-15 11:08

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Principal', max_length=10, verbose_name='Name of The branch')),
                ('address', models.TextField(verbose_name='Address of the branch')),
            ],
        ),
        migrations.AddField(
            model_name='remmit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 15), verbose_name='Remmittance Distribution Date'),
        ),
        migrations.AddField(
            model_name='remmit',
            name='mode',
            field=models.CharField(choices=[('C', 'Cash'), ('T', 'Transfer')], default='C', max_length=1, verbose_name='Mode of Transaction'),
        ),
        migrations.AddField(
            model_name='remmit',
            name='reciever',
            field=models.CharField(default=' ', max_length=30, verbose_name='Name of Benificiary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remmit',
            name='rem_country',
            field=models.CharField(default=' ', max_length=20, verbose_name='Name of remmitting country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remmit',
            name='sender',
            field=models.CharField(default=' ', max_length=30, verbose_name='Name of Remmitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remmit',
            name='exchange',
            field=models.CharField(choices=[('WU', 'Western Union'), ('MG', 'MoneyGram'), ('EM', 'Express Money'), ('RI', 'Ria'), ('EM', 'Placid')], default='WU', max_length=2, verbose_name='Name of Exchange house'),
        ),
    ]
