# Generated by Django 2.0.7 on 2018-07-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0004_auto_20180718_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangehouse',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of Exchange House'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.ExchangeHouse'),
        ),
    ]
