# Generated by Django 2.0.7 on 2018-07-18 09:31

from decimal import Decimal
from django.db import migrations, models
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0005_auto_20180718_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[rem.validators.validate_neg]),
        ),
    ]
