# Generated by Django 2.0.7 on 2018-07-22 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0006_auto_20180718_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=datetime.date(2018, 7, 22), verbose_name='Date of posting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remmit',
            name='date_edited',
            field=models.DateField(auto_now=True, verbose_name='Date of last modified'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 22), verbose_name='Remmittance Distribution Date'),
        ),
    ]
