# Generated by Django 2.0.7 on 2018-07-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0007_auto_20180722_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(default='0101', max_length=10, verbose_name='Branch Code'),
        ),
    ]
