# Generated by Django 2.0.7 on 2018-07-23 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0008_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(default='0101', max_length=4, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 23), verbose_name='Remmittance Distribution Date'),
        ),
    ]
