# Generated by Django 2.0.7 on 2018-07-24 10:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rem', '0010_auto_20180723_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 24), validators=[rem.validators.validate_post_date], verbose_name='Remmittance Distribution Date'),
        ),
    ]
