# Generated by Django 2.0.7 on 2018-07-26 06:55

import datetime
from django.db import migrations, models
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0011_auto_20180724_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='date_settle',
            field=models.DateField(null=True, validators=[rem.validators.validate_post_date], verbose_name='Remmittance Settement Date'),
        ),
        migrations.AddField(
            model_name='remmit',
            name='status',
            field=models.CharField(choices=[('ST', 'Setteled'), ('PS', 'Downloaded for settlement'), ('NS', 'Transfer')], default='NS', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 26), validators=[rem.validators.validate_post_date], verbose_name='Remmittance Distribution Date'),
        ),
    ]
