# Generated by Django 2.0.7 on 2018-07-30 12:37

import datetime
from django.db import migrations, models
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0012_auto_20180726_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 30), validators=[rem.validators.validate_post_date], verbose_name='Remmittance Distribution Date'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='status',
            field=models.CharField(choices=[('ST', 'Settled'), ('NS', 'Not Settled')], default='NS', max_length=2, verbose_name='Status'),
        ),
    ]
