# Generated by Django 2.0.7 on 2018-07-31 08:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rem', '0013_auto_20180730_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Branch', verbose_name='Branch of the Employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 7, 31), validators=[rem.validators.validate_post_date], verbose_name='Remmittance Distribution Date'),
        ),
    ]
