# Generated by Django 2.0.7 on 2018-08-05 07:03

import datetime
from django.db import migrations, models
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0015_auto_20180731_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of The Country')),
                ('code', models.CharField(max_length=20, verbose_name='Country code')),
            ],
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateField(default=datetime.date(2018, 8, 5), validators=[rem.validators.validate_post_date], verbose_name='Remmittance Distribution Date'),
        ),
    ]
