# Generated by Django 2.0.7 on 2018-08-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0016_auto_20180805_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='rem_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Country', verbose_name='Name of Country'),
        ),
    ]
