# Generated by Django 2.0.7 on 2018-08-16 12:36

from django.db import migrations, models
import django.utils.timezone
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0018_auto_20180813_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[rem.validators.validate_post_date], verbose_name='Remmittance Distribution Date'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of posting'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of last modified'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date_settle',
            field=models.DateTimeField(null=True, validators=[rem.validators.validate_post_date], verbose_name='Remmittance Settement Date'),
        ),
    ]
