# Generated by Django 2.0.7 on 2018-09-19 10:20

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0020_auto_20180903_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Payment'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.ExchangeHouse', verbose_name='Remittance channel'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Referene No./PIN/MTCN'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='sender',
            field=models.CharField(max_length=30, verbose_name='Name of Remitter'),
        ),
    ]
