# Generated by Django 2.0.7 on 2018-09-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0021_auto_20180919_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.ExchangeHouse', verbose_name='Channel of Remittance'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='reference',
            field=models.CharField(max_length=16, verbose_name='Referene No./PIN/MTCN'),
        ),
    ]
