# Generated by Django 2.0.7 on 2018-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0022_auto_20180920_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remmit',
            name='reference',
            field=models.CharField(max_length=16, unique=True, verbose_name='Referene No./PIN/MTCN'),
        ),
    ]
