# Generated by Django 2.0.7 on 2018-09-30 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rem', '0023_auto_20180920_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_resolved', models.DateTimeField(auto_now_add=True, verbose_name='Date of payment/rejection')),
                ('status', models.CharField(choices=[('P', 'Payment confirmed'), ('R', 'Rejected due to some reason')], default='R', max_length=1, verbose_name='Status')),
                ('comment', models.TextField(null=True, verbose_name='Reason for rejection or any other remarks')),
                ('date_settle', models.DateTimeField(null=True, validators=[rem.validators.validate_post_date], verbose_name='Date of settlement')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Receiver')),
                ('address', models.TextField(verbose_name='Address of Receiver')),
                ('dob', models.DateField(verbose_name='Date of Birth of Receiver')),
                ('cell', models.CharField(max_length=14, validators=[rem.validators.validate_mobile], verbose_name='Cell number of Receiver')),
            ],
        ),
        migrations.CreateModel(
            name='Requestpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date of request')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='date_settle',
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='status',
        ),
        migrations.AlterField(
            model_name='remmit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rem.Receiver', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='sender',
            field=models.CharField(max_length=50, verbose_name='Name of Remitter'),
        ),
        migrations.AddField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reqp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Requestpay'),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
