# Generated by Django 2.0.7 on 2018-10-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0026_auto_20181016_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestpay',
            old_name='date_create',
            new_name='datecreate',
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
