# Generated by Django 2.0.7 on 2018-10-29 11:47

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0031_auto_20181029_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='idno',
            field=models.CharField(max_length=17, validators=[rem.validators.validate_mobile], verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
