# Generated by Django 2.0.7 on 2018-10-29 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0037_auto_20181029_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='idexpire',
            field=models.DateField(null=True, verbose_name='Expiry date of Identification Document'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='idissue',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue date of Identification Document'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='idno',
            field=models.CharField(max_length=17, null=True, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='idtype',
            field=models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport'), ('BC', 'Birth Regestration Certificate')], default='NID', max_length=8, verbose_name='Type o Identification'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
