# Generated by Django 2.0.7 on 2018-10-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0039_auto_20181029_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reqp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rem.Requestpay'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
