# Generated by Django 2.0.7 on 2018-11-05 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0041_auto_20181031_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reqp',
            new_name='requestpay',
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
