# Generated by Django 2.0.7 on 2018-11-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0043_auto_20181105_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_resolved',
            new_name='dateresolved',
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
