# Generated by Django 2.0.7 on 2018-11-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0044_auto_20181106_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpay',
            name='resubmit_flag',
            field=models.BooleanField(default=False, verbose_name='Resubmit Yes/No'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
