# Generated by Django 2.0.7 on 2018-11-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0045_auto_20181111_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='western_trm_screenshot',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='western_trm/%Y/%m/%d/', verbose_name='Pre Transaction Receipt'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Remitting Country'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='rem_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Country', verbose_name='Remitting Country'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
