# Generated by Django 2.0.7 on 2018-11-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0046_auto_20181120_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='relationship',
            field=models.CharField(max_length=50, null=True, verbose_name='Relationship to Sender'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='status',
            field=models.CharField(choices=[('RV', 'Request to be Processed'), ('RJ', 'Request Rejected'), ('PD', 'Amount Payable to Customer')], default='RV', max_length=2, verbose_name='Request Status'),
        ),
    ]
