# Generated by Django 2.0.7 on 2018-11-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0047_auto_20181126_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='payment',
            name='agent_screenshot',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/%Y/%m/%d/', verbose_name='Agent Copy'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_screenshot',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='western_trm/%Y/%m/%d/', verbose_name='Customer Copy'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='relationship',
            field=models.CharField(default='hello', max_length=50, null=True, verbose_name='Relationship to Sender'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
