# Generated by Django 2.0.7 on 2018-11-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0048_auto_20181128_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='purpose',
            field=models.CharField(max_length=50, null=True, verbose_name='Purpose of Transaction'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='relationship',
            field=models.CharField(max_length=50, null=True, verbose_name='Relationship to Sender'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
