# Generated by Django 2.0.7 on 2018-12-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0052_auto_20181210_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.0.1', verbose_name='User IP Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestpay',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.0.1', verbose_name='User IP Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
