# Generated by Django 2.0.7 on 2019-05-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0059_auto_20190120_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='idissue',
            field=models.DateField(null=True, verbose_name='Issue date of Identification Document'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
