# Generated by Django 2.0.7 on 2019-09-16 04:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0064_auto_20190522_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of The booth')),
                ('code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Booth Code')),
                ('address', models.TextField(verbose_name='Address of the branch')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Branch', verbose_name='Branch of the Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='receiver',
            name='idtype',
            field=models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport'), ('BC', 'Birth Regestration Certificate'), ('DL', 'Driving License')], default='NID', max_length=8, verbose_name='Type o Identification'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
