# Generated by Django 2.0.7 on 2019-09-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0065_auto_20190916_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='booth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Booth', verbose_name='Booth of the Employee'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Branch', verbose_name='Branch of the Employee'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='idtype',
            field=models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport'), ('BC', 'Birth Regestration Certificate'), ('DL', 'Driving License')], default='NID', max_length=8, verbose_name='Type of Identification'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
