# Generated by Django 2.2.5 on 2019-10-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0067_auto_20190923_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='date_sending',
            field=models.DateField(null=True, verbose_name='Date of posting'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Booth', verbose_name='Booth of the Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cell',
            field=models.CharField(max_length=14, validators=[rem.validators.validate_mobile], verbose_name='Cell number of Employee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_settle',
            field=models.DateTimeField(blank=True, null=True, validators=[rem.validators.validate_post_date], verbose_name='Date of settlement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
