# Generated by Django 2.2.5 on 2019-10-10 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0068_auto_20191010_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date_sending',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 10, 31, 46, 929984, tzinfo=utc), verbose_name='Date of posting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
