# Generated by Django 2.2.5 on 2019-10-10 12:32

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0070_auto_20191010_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='cash_incentive_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Cash Incentive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date_sending',
            field=models.DateField(verbose_name='Date of Sending Remittance from Abroad'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
