# Generated by Django 2.2.5 on 2019-10-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0072_auto_20191013_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='date_cash_incentive_settlement',
            field=models.DateField(null=True, verbose_name='Date of Cash Incentive Settlement'),
        ),
        migrations.AddField(
            model_name='remmit',
            name='unpaid_cash_incentive_reason',
            field=models.CharField(help_text='This field is mandatory if you mark cash incentive as unpaid', max_length=50, null=True, verbose_name='Reason for not paying cash incentive'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='cash_incentive_status',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], help_text="Please select 'Held' if required documents not collected and incentive not paid", max_length=1, verbose_name='Cash Incentive Status'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
