# Generated by Django 2.2.5 on 2019-10-16 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0073_auto_20191014_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ad_code',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Branch Code'),
        ),
        migrations.AddField(
            model_name='branch',
            name='division',
            field=models.CharField(default='Haha', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Branch Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Booth'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='date_cash_incentive_settlement',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Cash Incentive Settlement'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='unpaid_cash_incentive_reason',
            field=models.CharField(blank=True, help_text='This field is mandatory if you mark cash incentive as unpaid', max_length=50, null=True, verbose_name='Reason for not paying cash incentive'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
