# Generated by Django 2.2.5 on 2019-10-21 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0074_auto_20191016_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='ac_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^01[0-6][1-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number of the receiver (If any)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ad_code',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='AD Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='division',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Required documents must be collected and retained for paying inentive against Remittances valuing more than USD 1500.00 or equivalent', max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Remittance'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
