# Generated by Django 2.2.5 on 2019-10-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0076_auto_20191021_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='ad_code',
            new_name='ad_fi_code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='division',
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
