# Generated by Django 2.2.5 on 2019-10-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20191023_1322'),
        ('rem', '0078_auto_20191023_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='currency',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='schedules.Currency', verbose_name='Currency of Remittance'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
