# Generated by Django 2.2.5 on 2020-01-23 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_bank'),
        ('rem', '0084_auto_20191202_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Required documents must be collected and retained for paying inentive against Remittances valuing more than BDT 1,50,000.00', max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Remittance'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_claim', models.DateTimeField(auto_now_add=True, verbose_name='Date of Claim')),
                ('statement_check', models.BooleanField(verbose_name='Benificary Account Statement checked ?')),
                ('account_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^01[0-6][1-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Benificary Account number')),
                ('account_title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Benificary Account number')),
                ('channel', models.CharField(choices=[('B', 'BEFTN'), ('R', 'RTGS')], max_length=1, verbose_name='Channel of remittance')),
                ('document_check', models.BooleanField(verbose_name='Remitters document checked ?')),
                ('sender_name', models.CharField(max_length=100, verbose_name="Remitter's Name")),
                ('idtype', models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport'), ('BC', 'Birth Regestration Certificate'), ('DL', 'Driving License')], max_length=8, verbose_name='Type of Identification')),
                ('idno', models.CharField(max_length=17, unique=True, verbose_name='ID Number')),
                ('letter_check', models.BooleanField(verbose_name="Beneficiary's Letter of Incentive Claim Received?")),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Branch')),
                ('collecting_bank', models.ForeignKey(limit_choices_to={'type': 'PRIVATE COMMERCIAL BANK'}, on_delete=django.db.models.deletion.CASCADE, to='schedules.Bank')),
                ('issuing_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Country')),
            ],
        ),
    ]
