# Generated by Django 2.2.5 on 2020-01-26 11:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0086_auto_20200126_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='idno',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='idtype',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='issuing_country',
        ),
        migrations.AddField(
            model_name='claim',
            name='doc_expire',
            field=models.DateField(default=datetime.date(2020, 1, 26), verbose_name="Expiry date of Remitter's Other Document"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='doc_issuing_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doc_issuing_country', to='rem.Country', verbose_name='Other Document Issuing Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='doc_no',
            field=models.CharField(default='123', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only Alphabet and numeric characters are allowed.')], verbose_name="Remitter's Other Document Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='doc_type',
            field=models.CharField(default='None', max_length=50, verbose_name="Remitter's Other Document Type"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='passport_expire',
            field=models.DateField(default=datetime.date(2020, 1, 26), verbose_name="Expiry date of Remitter's Passport"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='passport_issuing_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rem.Country', verbose_name='Passport Issuing Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='passport_no',
            field=models.CharField(default='123', max_length=17, unique=True, verbose_name='Passport Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='account_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^01[0-6][1-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Benificary Account Number'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='account_title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Benificary Account Title'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='channel',
            field=models.CharField(choices=[('B', 'BEFTN'), ('R', 'RTGS')], max_length=1, verbose_name='Channel of A/C Credit'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='collecting_bank',
            field=models.ForeignKey(limit_choices_to={'type': 'PRIVATE COMMERCIAL BANK'}, on_delete=django.db.models.deletion.CASCADE, to='schedules.Bank', verbose_name='Collecting Bank'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='document_check',
            field=models.BooleanField(help_text="Remitter's documents must be checked before submission of cash incentive claim", verbose_name='Remitters Document Checked ?'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='letter_check',
            field=models.BooleanField(help_text="Beneficiary's Letter of Incentive Claim must be obtained before submissionof claim", verbose_name="Beneficiary's Letter of Incentive Claim Received?"),
        ),
        migrations.AlterField(
            model_name='claim',
            name='sender_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name="Remitter's Name"),
        ),
        migrations.AlterField(
            model_name='claim',
            name='statement_check',
            field=models.BooleanField(help_text='Beneficiary account statement must be checked before submission of cash incentive claim', verbose_name='Benificary Account Statement checked ?'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
