# Generated by Django 2.2.5 on 2020-01-27 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0087_auto_20200126_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='visa_check',
            field=models.BooleanField(default=False, help_text=' ', verbose_name='Visa Required for Travelling to Bangladesh?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
