# Generated by Django 2.2.5 on 2020-01-29 06:42

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0088_auto_20200127_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='remittance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Required documents must be collected and retained for paying inentive against Remittances valuing more than BDT 1,50,000.00', max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Remittance in BDT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='account_title',
            field=models.CharField(max_length=100, verbose_name='Benificary Account Title'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='doc_expire',
            field=models.DateField(verbose_name="Expiry Date of Remitter's Other Document"),
        ),
        migrations.AlterField(
            model_name='claim',
            name='letter_check',
            field=models.BooleanField(help_text="Beneficiary's Letter of Incentive Claim must be obtained before submission of claim", verbose_name="Beneficiary's Letter of Incentive Claim Received?"),
        ),
        migrations.AlterField(
            model_name='claim',
            name='passport_expire',
            field=models.DateField(verbose_name="Expiry Date of Remitter's Passport"),
        ),
        migrations.AlterField(
            model_name='claim',
            name='visa_check',
            field=models.BooleanField(help_text='Applicable & Mandatory to obtain for Foreign Passport Holders only', null=True, verbose_name=' "NO Visa Required to Travel Bangladesh" Document Obtained?'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
