# Generated by Django 2.2.5 on 2020-01-29 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0089_auto_20200129_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='date_account_credit',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 13, 22, 41, 375353), verbose_name='Date of Account Credit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
