# Generated by Django 2.2.5 on 2020-01-30 09:46

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0090_auto_20200129_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='date_forward',
            field=models.DateTimeField(null=True, verbose_name='Date of Claim forwarded to collecting Bank'),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_resolved',
            field=models.DateTimeField(null=True, verbose_name='Date of Claim realized from collecting Bank'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='doc_expire',
            field=models.DateField(validators=[rem.validators.validate_expire_date], verbose_name="Expiry Date of Remitter's Other Document"),
        ),
        migrations.AlterField(
            model_name='claim',
            name='passport_expire',
            field=models.DateField(validators=[rem.validators.validate_expire_date], verbose_name="Expiry Date of Remitter's Passport"),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
