# Generated by Django 2.2.5 on 2020-02-26 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0092_auto_20200203_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='code',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Booth Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ad_fi_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='AD Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(default='0101', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_forward',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Claim forwarded to collecting Bank'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Claim realized from collecting Bank'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
