# Generated by Django 2.2.12 on 2020-04-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0093_auto_20200226_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='father_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name="Father's name of Receiver"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'Other')], default='O', max_length=1, verbose_name='Gender of Receiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='mother_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name="Mother's of Receiver"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rem.Country', verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='profession',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Profession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='spouse_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Spouse name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='collecting_bank',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 'PRIVATE COMMERCIAL BANK'), ('type', 'STATE-OWNED COMMERCIAL BANK'), ('type', 'FOREIGN COMMERCIAL BANKS'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='schedules.Bank', verbose_name='Collecting Bank'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
