# Generated by Django 2.2.12 on 2020-04-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0094_auto_20200422_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's name of Receiver"),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spouse name'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
