# Generated by Django 2.2.12 on 2020-05-12 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0095_auto_20200422_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangehouse',
            name='gl_key',
            field=models.CharField(default='00000000000', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='GL Key of Exchange House'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiver',
            name='nationality',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='rem.Country', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
