# Generated by Django 2.2.5 on 2020-06-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0098_auto_20200601_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangehouse',
            name='gl_key_name',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Name of Exchange House GL Key Head'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangehouse',
            name='cash_incentive_gl_key_name',
            field=models.CharField(max_length=50, verbose_name='Name of Cash incentive GL Key Head'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
