# Generated by Django 2.2.5 on 2021-01-24 11:01

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0101_auto_20201201_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.CreateModel(
            name='CashIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_incentive_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Cash Incentive')),
                ('date_cash_incentive_paid', models.DateTimeField(blank=True, null=True, verbose_name='Date of Cash Incentive payment')),
                ('date_cash_incentive_settlement', models.DateField(blank=True, null=True, verbose_name='Date of Cash Incentive Settlement')),
                ('unpaid_cash_incentive_reason', models.CharField(blank=True, help_text='This field is mandatory if you mark cash incentive as unpaid', max_length=50, null=True, verbose_name='Reason for not paying cash incentive')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit')),
            ],
        ),
    ]
