# Generated by Django 2.2.5 on 2021-03-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0103_auto_20210125_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='sender_gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender of the Sender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='entry_category',
            field=models.CharField(choices=[('P', 'Payment'), ('U', 'Non Payment'), ('NA', 'Cash Incentive Not Applicable')], max_length=1, verbose_name='Entry Category'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
