# Generated by Django 2.2.5 on 2021-04-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0108_auto_20210329_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangehouse',
            name='verbose_name',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Full Name of the Exchangehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='partial_payment_status',
            field=models.BooleanField(default=False, verbose_name='Partial Cash Incentive Payment?'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
