# Generated by Django 2.2.16 on 2021-10-11 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0115_auto_20210810_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiver',
            options={'verbose_name': 'Benificiary of Remittance'},
        ),
        migrations.AlterModelOptions(
            name='remmit',
            options={'verbose_name': 'Remittance'},
        ),
        migrations.AddField(
            model_name='remmit',
            name='screenshot',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/%Y/%m/%d/', verbose_name='Agent Copy'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='sender_occupation',
            field=models.CharField(choices=[('S', 'SERVICE'), ('B', 'BUSINESS'), ('O', 'OTHER')], help_text='Service/ Business etc.', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Occupation of Remitter'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
