# Generated by Django 2.2.16 on 2021-12-20 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0117_auto_20211012_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='screenshot',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='', verbose_name='Agent Copy'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.CreateModel(
            name='Encashment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Something ', max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Encashment')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Something ', max_digits=6, validators=[rem.validators.validate_neg], verbose_name='Rate of Encashment')),
                ('cashin_category', models.CharField(choices=[('P', 'Paid'), ('U', 'Not Paid'), ('NA', 'Not Applicable')], max_length=2, verbose_name='Cash Incentive Payment Status')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Reason for not paying cash incentive')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit')),
            ],
        ),
    ]
