# Generated by Django 2.2.16 on 2021-12-22 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0121_auto_20211222_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason for not paying cash incentive'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^01[0-7][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number (Full)')),
                ('title', models.CharField(max_length=100, verbose_name='Account Ttile')),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Booth')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Branch')),
            ],
        ),
    ]
