# Generated by Django 2.2.16 on 2022-01-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0126_auto_20211228_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='mariner_status',
            field=models.BooleanField(default=False, verbose_name='Mariner/ Cabin Crew Remittance?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='encashment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Encashment'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='entry_category',
            field=models.CharField(choices=[('P', 'Pay Now'), ('U', 'Pay Later'), ('NA', 'Not Applicable')], max_length=2, verbose_name='Cash Incentive Payment Status'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='cash_incentive_status',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], max_length=2, verbose_name='Cash Incentive Status'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
