# Generated by Django 2.2.16 on 2022-01-04 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0127_auto_20220104_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='sender_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Sender's Bank"),
        ),
        migrations.AddField(
            model_name='remmit',
            name='sender_bank_swift',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{8,10}$', 'Please provide a valid SWIFT BIC')], verbose_name="Sender's Bank's SWIFT BIC"),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='mariner_status',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Mariner/ Cabin Crew Remittance?'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
