# Generated by Django 2.2.16 on 2022-01-05 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0128_auto_20220104_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(0|5)[0-9][0-7][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number (15 Digit)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Account Title'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Something ', max_digits=8, validators=[rem.validators.validate_neg], verbose_name='Rate of Encashment'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='profession',
            field=models.CharField(choices=[('S', 'SERVICE'), ('B', 'BUSINESS'), ('O', 'OTHER')], max_length=100, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='cash_incentive_status',
            field=models.CharField(choices=[('P', 'Pay Now'), ('U', 'Pay Later'), ('NA', 'Not Applicable')], max_length=2, verbose_name='Cash Incentive Status'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='sender_bank_swift',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{11}$', 'Please provide a valid SWIFT BIC')], verbose_name="Sender's Bank's SWIFT BIC"),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
