# Generated by Django 2.2.16 on 2022-03-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0131_auto_20220302_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remmit',
            name='ordering_bank_name',
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='ordering_bank_swift',
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='sender_bank',
        ),
        migrations.RemoveField(
            model_name='remmit',
            name='sender_bank_swift',
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
