# Generated by Django 2.2.16 on 2022-03-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20211012_1519'),
        ('rem', '0132_auto_20220302_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='sender_bank',
            field=models.ForeignKey(help_text='Ordering Institution: F52A for remittance through SWIFT', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Bank', verbose_name="Sender's Bank/ Ordering Institution"),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
