# Generated by Django 2.2.16 on 2022-03-08 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0133_auto_20220302_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.CreateModel(
            name='Foreignbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ordering Institution: F52A for remittance through SWIFT', max_length=60, unique=True, verbose_name='Name of the FI')),
                ('swift_bic', models.CharField(help_text="Ordering Institution's SWIFT BIC: F52A for remittance through SWIFT", max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{11}$', 'Please provide a valid SWIFT BIC')], verbose_name='SWIFT BIC')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rem.Country', verbose_name='Country of the Bank')),
            ],
        ),
    ]
