# Generated by Django 2.2.16 on 2022-03-22 07:05

from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0136_auto_20220314_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincentive',
            name='encashment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Encashment'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Something ', max_digits=20, validators=[rem.validators.validate_neg], verbose_name='Amount of Encashment in FC'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Something ', max_digits=8, validators=[rem.validators.validate_neg], verbose_name='Rate of Encashment to BDT'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='sender_bank',
            field=models.ForeignKey(help_text='Ordering Institution: F52A for remittance through SWIFT. If not listed, you can add foreign bank', null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Foreignbank', verbose_name="Sender's Bank/ Ordering Institution"),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
