# Generated by Django 2.2.16 on 2022-05-16 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0138_auto_20220329_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(0|5)[0-9][0-8][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number (15 Digit)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ad_fi_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='AD FI Code'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='account_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(0|5)[0-9][0-8][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Benificary Account Number'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='ac_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(0|5)[0-9][0-8][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number of the receiver (If any)'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='mother_name',
            field=models.CharField(max_length=100, verbose_name="Mother's Name of Receiver"),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='reference',
            field=models.CharField(help_text="Referene No./PIN/MTCN/ For SWIFT - Sender's reference: F20A, <br> For Cash FC Deposit Remittance: C[BRANCH CODE]-YYYY-MM-DD-[Serial No (2 Digit)] e.g. C0101-2022-16-05-01", max_length=20, unique=True, verbose_name='Referene No./PIN/MTCN'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='relationship',
            field=models.CharField(choices=[('FM', 'Family'), ('FR', 'Friend'), ('BA', 'Business Associate'), ('CL', 'Client'), ('EM', 'Employee'), ('ER', 'Employer'), ('AC', 'Acquaintance'), ('SL', 'Self')], max_length=50, null=True, verbose_name="Benificiary's relationship to Sender"),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='sender_bank',
            field=models.ForeignKey(blank=True, help_text='Ordering Institution: F52A for remittance through SWIFT. If not listed, you can add foreign bank', null=True, on_delete=django.db.models.deletion.CASCADE, to='rem.Foreignbank', verbose_name="Sender's Bank/ Ordering Institution"),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
