# Generated by Django 2.2.16 on 2022-06-22 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0143_auto_20220606_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ad_fi_code',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='AD FI Code'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='cash_incentive_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[rem.validators.validate_neg, django.core.validators.MaxValueValidator(25000.0)], verbose_name='Amount of Cash Incentive'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Required documents must be collected and retained for paying inentive against Remittances valuing more than BDT 5,00,000.00 or USD 5,000.00 or equivalent FC', max_digits=20, validators=[rem.validators.validate_neg, django.core.validators.MaxValueValidator(1000000.0)], verbose_name='Amount of Remittance'),
        ),
        migrations.AlterField(
            model_name='remmit',
            name='cash_incentive_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[rem.validators.validate_neg, django.core.validators.MaxValueValidator(25000.0)], verbose_name='Amount of Cash Incentive'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
