# Generated by Django 2.2.16 on 2022-08-08 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_auto_20220606_1443'),
        ('rem', '0144_auto_20220622_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='remmit',
            name='fdd_bank',
            field=models.ForeignKey(blank=True, help_text='Mandatory for remittance through FDD', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Bank', verbose_name='FDD issuer Bank'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(0|5|6)[0-9][0-8][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number (15 Digit)'),
        ),
        migrations.AlterField(
            model_name='cashincentive',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='account_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(0|5|6)[0-9][0-8][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Benificary Account Number'),
        ),
        migrations.AlterField(
            model_name='encashment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='ac_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(0|5|6)[0-9][0-8][0-9][2-3][0-9]{10}$', 'Please provide a valid NRBC account number')], verbose_name='Account Number of the receiver (If any)'),
        ),
        migrations.AlterField(
            model_name='remittanceupdatehistory',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit', verbose_name='Remittance Entry'),
        ),
        migrations.AlterField(
            model_name='requestpay',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.Remmit'),
        ),
    ]
