# Generated by Django 2.2.5 on 2019-12-02 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20191027_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='short',
            field=models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Short Code'),
            preserve_default=False,
        ),
    ]
