# Generated by Django 2.2.5 on 2020-01-22 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_currency_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of Bank')),
                ('fi_id', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='FI ID')),
                ('type', models.CharField(max_length=60, verbose_name='Type of Institution')),
            ],
        ),
    ]
