# Generated by Django 2.2.5 on 2021-03-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('BCS', 'BC SELLING'), ('TTC', 'TT CLEAN')], max_length=3, verbose_name='Type of Exchange Rate')),
                ('date', models.DateField(verbose_name='Date of Entry')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Currency')),
            ],
        ),
    ]
