# Generated by Django 2.2.5 on 2021-03-24 10:43

from django.db import migrations, models
import rem.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[rem.validators.validate_neg], verbose_name='Exchange Rate in BDT'),
            preserve_default=False,
        ),
    ]
