# Generated by Django 2.2.5 on 2021-06-10 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='short',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')], verbose_name='Short Code'),
        ),
    ]
