# Generated by Django 2.2.16 on 2021-10-12 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20210610_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='ccy_id',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='CCY ID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='cur_code',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of Currenct'),
        ),
    ]
