# Generated by Django 2.2.16 on 2021-10-12 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20211012_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='cur_code',
            field=models.CharField(max_length=3, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Currency Code'),
        ),
    ]
