# Generated by Django 2.2.16 on 2022-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20211012_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(choices=[('TTC', 'TT CLEAN'), ('BCS', 'BC SELLING')], max_length=3, verbose_name='Type of Exchange Rate'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('date', 'rate_type')},
        ),
    ]
