# Generated by Django 2.2.16 on 2022-06-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20220606_1316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('currency', 'rate_type')},
        ),
    ]
