# Generated by Django 2.2.16 on 2022-06-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_auto_20220606_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('date', 'currency', 'rate_type')},
        ),
    ]
